projectName: pangeo-binder-prod

binderhub:
  config:
    BinderHub:
      build_node_selector:
        hub.jupyter.org/node-purpose: user
      hub_url: https://hub.binder.pangeo.io
      badge_base_url: https://binder.pangeo.io
      image_prefix: gcr.io/pangeo-181919/prod-
      google_analytics_code: UA-120544092-2
      google_analytics_domain: binder.pangeo.io
  nodeSelector:
    hub.jupyter.org/node-purpose: core

  ingress:
    enabled: true
    hosts:
      - binder.pangeo.io
    annotations:
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
      cert-manager.io/issuer: letsencrypt-production
      https:
        enabled: true
        type: nginx

    tls:
      - secretName: prod-binder-pangeo-io-tls
        hosts:
          - binder.pangeo.io
  dind:
    hostLibDir: /var/lib/dind/prod
    hostSocketDir: /var/run/dind/prod

  jupyterhub:
    proxy:
      nodeSelector:
        hub.jupyter.org/node-purpose: core
    ingress:
      enabled: true
      hosts:
        - hub.binder.pangeo.io
      annotations:
        kubernetes.io/ingress.class: nginx
        kubernetes.io/tls-acme: "true"
        cert-manager.io/issuer: letsencrypt-production
        https:
          enabled: true
          type: nginx
      tls:
        - secretName: hub-binder-pangeo-io-tls
          hosts:
            - hub.binder.pangeo.io

    singleuser:
      extraEnv:
        DASK_GATEWAY__ADDRESS: "https://hub.binder.pangeo.io/services/dask-gateway/"
        DASK_GATEWAY__PROXY_ADDRESS: "gateway://traefik-prod-dask-gateway.prod:80"

    hub:
      services:
        dask-gateway:
          # This makes the gateway available at ${HUB_URL}/services/dask-gateway
          url: http://traefik-prod-dask-gateway.prod

ingress:
  enabled: true
  hosts:
     - binder.pangeo.io
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    cert-manager.io/issuer: letsencrypt-production
    https:
      enabled: true
      type: nginx
  tls:
    - secretName: prod-binder-pangeo-io-tls
      hosts:
       - binder.pangeo.io


nginx-ingress:
  controller:
    service:
      loadBalancerIP: 35.226.186.40

kube-prometheus-stack:
  grafana:
    ingress:
      enabled: true
      hosts:
        - grafana.binder.pangeo.io
      annotations:
        kubernetes.io/ingress.class: nginx
        kubernetes.io/tls-acme: "true"
        cert-manager.io/issuer: letsencrypt-production
      tls:
        - secretName: grafana.binder.pangeo.io-tls
          hosts:
            - grafana.binder.pangeo.io
