projectName: pangeo-binder-staging

binderhub:
  config:
    BinderHub:
      build_node_selector:
        hub.jupyter.org/node-purpose: user
      hub_url: https://hub.staging.binder.pangeo.io
      badge_base_url: https://staging.binder.pangeo.io
      image_prefix: gcr.io/pangeo-181919/staging-

  nodeSelector:
    hub.jupyter.org/node-purpose: core

  ingress:
    hosts:
      - staging.binder.pangeo.io

  dind:
    hostLibDir: /var/lib/dind/staging
    hostSocketDir: /var/run/dind/staging

  jupyterhub:
    proxy:
      nodeSelector:
        hub.jupyter.org/node-purpose: core
    ingress:
      hosts:
        - hub.staging.binder.pangeo.io
      tls:
        - secretName: kubelego-tls-jupyterhub-staging
          hosts:
            - hub.staging.binder.pangeo.io
    scheduling:
      userScheduler:
        enabled: false
    hub:
      resources:
        requests:
          cpu: "0.1"
          memory: 125Mi
      services:
        dask-gateway:
          # This makes the gateway available at ${HUB_URL}/services/dask-gateway
          url: http://web-public-staging-dask-gateway
      extraEnv:
        DASK_GATEWAY__ADDRESS: "https://hub.staging.binder.pangeo.io/services/dask-gateway/"

    proxy:
      chp:
        resources:
          requests:
            memory: 100Mi
            cpu: "0.1"
      nginx:
        resources:
          requests:
            memory: 100Mi
            cpu: "0.1"
kube-lego:
  nodeSelector:
    hub.jupyter.org/node-purpose: core

nginx-ingress:
  controller:
    service:
      loadBalancerIP: 35.224.187.103
