projectName: pangeo-binder-staging

binderhub:
  config:
    BinderHub:
      build_node_selector:
        hub.jupyter.org/node-purpose: user
      hub_url: https://hub.staging.binder.pangeo.io
      badge_base_url: https://staging.binder.pangeo.io
      image_prefix: gcr.io/pangeo-181919/staging-

  nodeSelector:
    hub.jupyter.org/node-purpose: core

  ingress:
    enabled: true
    hosts:
      - staging.binder.pangeo.io
    annotations:
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
      cert-manager.io/issuer: letsencrypt-production
      https:
        enabled: true
        type: nginx
    tls:
      - secretName: staging-binder-pangeo-io-tls
        hosts:
          - staging.binder.pangeo.io

  dind:
    hostLibDir: /var/lib/dind/staging
    hostSocketDir: /var/run/dind/staging

  jupyterhub:
    proxy:
      nodeSelector:
        hub.jupyter.org/node-purpose: core
    ingress:
      enabled: true
      hosts:
        - hub.staging.binder.pangeo.io
      annotations:
        kubernetes.io/ingress.class: nginx
        kubernetes.io/tls-acme: "true"
        cert-manager.io/issuer: letsencrypt-production
        https:
          enabled: true
          type: nginx
      tls:
         - secretName: hub-staging-binder-pangeo-io-tls
           hosts:
            - hub.staging.binder.pangeo.io

    scheduling:
      userScheduler:
        enabled: false
    singleuser:
      extraEnv:
        DASK_GATEWAY__ADDRESS: "https://hub.staging.binder.pangeo.io/services/dask-gateway/"
        DASK_GATEWAY__PROXY_ADDRESS: "gateway://traefik-staging-dask-gateway.staging:80"

    hub:
      resources:
        requests:
          cpu: "0.1"
          memory: 125Mi
      services:
        dask-gateway:
          # This makes the gateway available at ${HUB_URL}/services/dask-gateway
          url: http://traefik-staging-dask-gateway.staging

    proxy:
      chp:
        resources:
          requests:
            memory: 100Mi
            cpu: "0.1"
      nginx:
        resources:
          requests:
            memory: 100Mi
            cpu: "0.1"

nginx-ingress:
  controller:
    service:
      loadBalancerIP: 35.224.187.103

prometheus-operator:
  prometheus:
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 0m
        memory: 0Gi
  grafana:
    resources:
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 0m
        memory: 0Gi
    ingress:
      enabled: true
      hosts:
        - grafana.staging.binder.pangeo.io
      annotations:
        kubernetes.io/ingress.class: nginx
        kubernetes.io/tls-acme: "true"
        cert-manager.io/issuer: letsencrypt-production
      tls:
        - secretName: grafana.staging.binder.binder.io-tls
          hosts:
            - grafana.staging.binder.binder.io

ingress:
  enabled: true
  hosts:
     - staging.binder.pangeo.io
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    cert-manager.io/issuer: letsencrypt-production
    https:
      enabled: true
      type: nginx
  tls:
    - secretName: staging-binder-pangeo-io-tls
      hosts:
       - staging.binder.pangeo.io
